# Generated by Django 4.2.3 on 2023-11-16 09:36

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_otp_request_time_user_reset_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=users.models.upload_to),
        ),
        migrations.AlterField(
            model_name='user',
            name='reset_otp',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
