# Generated by Django 4.2.3 on 2024-03-22 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_expired_user_subscription_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='subscription_status',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
