# Generated by Django 4.2.3 on 2024-03-23 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_subscription_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='used_free_trial',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
