# Generated by Django 4.2.3 on 2024-06-06 09:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_user_email_otp_user_email_otp_request_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='subscription_due_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
