# Generated by Django 4.2.3 on 2024-03-22 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='identity',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
