# Generated by Django 4.2.3 on 2024-07-02 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_customer_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='final_customer_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
