# Generated by Django 4.2.3 on 2024-07-02 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_customer_final_customer_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='billing_request_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
