# Generated by Django 4.2.3 on 2024-07-02 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0005_customer_billing_request_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='subscription_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
