# Generated by Django 4.2.3 on 2023-10-12 01:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import processplant.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='processPlant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('longitude', models.FloatField()),
                ('latitude', models.FloatField()),
                ('plant_image', models.ImageField(upload_to=processplant.models.upload_to)),
                ('meta_data', models.JSONField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proccessed_plant_requests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
