# Generated by Django 4.2.3 on 2023-10-15 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processplant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='processplant',
            name='humidity',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='processplant',
            name='temperature',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
