# Generated by Django 4.2.3 on 2023-11-29 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processplant', '0002_processplant_humidity_processplant_temperature'),
    ]

    operations = [
        migrations.AddField(
            model_name='processplant',
            name='recommendation',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
