# Generated by Django 4.2.3 on 2023-12-01 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processplant', '0003_processplant_recommendation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processplant',
            name='recommendation',
            field=models.TextField(blank=True, null=True),
        ),
    ]
