# Generated by Django 4.2.3 on 2024-01-26 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processplant', '0004_alter_processplant_recommendation'),
    ]

    operations = [
        migrations.AddField(
            model_name='processplant',
            name='image_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
