# Generated by Django 4.2.3 on 2024-02-21 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processplant', '0005_processplant_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='processplant',
            name='soil_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='processplant',
            name='sun_frequency',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='processplant',
            name='symptoms',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='processplant',
            name='water_frequency',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
